ff: write error messages to stderr, add usage

diff --git a/ff b/ff
--- a/ff
+++ b/ff
@@ -2,9 +2,11 @@
 # Find files by filename substring under current/specified directories
 
 RCFILE=".ffrc"
+USAGE="usage: ff [DIR] SEARCHSTR"
 
 if [ "$#" -lt 1 ]; then
-  echo "Missing required search term"
+  echo "Missing required search term." >&2
+  echo "$USAGE" >&2
   exit 1
 elif [ "$#" -eq 1 ]; then
   FFROOTS=.
